### ISSUE TITLE
Enable compression on producer

### ISSUE THREAD

**Issue by jobetdelima** [fede1024/kafka-benchmark#4]
Hello,

I wanted to try enabling compression on the producer, so I added "compression.type: snappy" in the config file, like below:

  msg_bursts_base_snappy:
    repeat_times: 5
    repeat_pause: 10
    topic: test_snappy_topic
    message_size: 4000
    message_count: 100000
    threads: 6
    producer: BaseProducer
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.messages: 1000000
      queue.buffering.max.ms: 100
      compression.type: snappy

Unfortunately, I ended up with the below error:
kafka-benchmark --config producer_benchmark_config.yaml --scenario msg_bursts_base_snappy
Scenario: msg_bursts_base_snappy, repeat 5 times, 10s pause after each
thread 'thread '<unnamed><unnamed>thread '' panicked at '' panicked at '<unnamed>Producer creation failed: KafkaError (Client config error: No such configuration property: "compression.type" compression.type snappy)Producer creation failed: KafkaError (Client config error: No such configuration property: "compression.type" compression.type snappy)' panicked at '', ', Producer creation failed: KafkaError (Client config error: No such configuration property: "compression.type" compression.type snappy)src/libcore/result.rssrc/libcore/result.rs', :thread 'src/libcore/result.rs:906<unnamed>:906:906:' panicked at '4:4Producer creation failed: KafkaError (Client config error: No such configuration property: "compression.type" compression.type snappy)4

Is there a way for me to enable compression?

Thanks!

**Comment by fede1024** [comment]
The correct name is `compression.codec` (see [rdkafka docs](https://docs.rs/rdkafka/0.14.0/rdkafka/producer/index.html#producer-configuration) or [librdkafka confguration parameters](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)).

I'll add a link to those pages in the README.

**Comment by jobetdelima** [comment]
Thanks! Let me try that. I just got it from https://kafka.apache.org/documentation/ under the "producer Config" section. I guess that's outdated?

**Comment by fede1024** [comment]
That's the Java producer documentation. The Rust producer, which is based on [librdkafka](https://github.com/edenhill/librdkafka), has different configuration parameters.

**Comment by jobetdelima** [comment]
Thanks.  BTW, is there a scenario set-up that would allow me to submit messages in batches? It doesn't look like enabling compression is affecting the metrics but I'm thinking perhaps it's because the messages are being sent one-by-one right away instead of in batches.

**Comment by fede1024** [comment]
Messages are sent in batches by default. See: https://fede1024.github.io/rust-rdkafka/rdkafka/producer/index.html#buffering

What configuration are you using? For higher throughput i recommend something like:
```yaml
producer_config:
  queue.buffering.max.messages: 1000000
  queue.buffering.max.ms: 100
```

**Comment by jobetdelima** [comment]
I see. I'm using the below config:
```
msg_bursts_base:
    repeat_times: 5
    repeat_pause: 10
    topic: test_topic
    message_size: 4000
    message_count: 100000
    threads: 6
    producer: BaseProducer
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.messages: 1000000
      queue.buffering.max.ms: 100
```
And saw almost the same metrics when I added `compression.codec: snappy`.

I just changed `queue.buffering.max.ms` from 100 to 0, and now I do see that enabling compression affects the metrics.

It's interesting that setting it to 100 seems to produce the best throughput.

Thanks for your help!
